services:
  # MySQL 8.0 Database
  # Placeholder for other databases
  # mysql:
  postgresql:
    image: percona/percona-distribution-postgresql:18.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crossql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crossql-network
  # mongodb:
  # cassandra:
volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  cassandra_data:
    driver: local

networks:
  crossql-network:
    driver: bridge