global:
  scrape_interval: 5s

scrape_configs:
  - job_name: crossql-engine
    metrics_path: /metrics
    static_configs:
      - targets: ["crossql-engine:7070"]
    authorization:
      type: Bearer
      credentials: test-key
